### ISSUE TITLE
Update！

### ISSUE THREAD

**Issue by ShangHuanqing** [Mr-SPM/code-creator-server#2]
### 作者更新速度太慢了 
给你分配任务：
- [ ] 添加新功能
- [ ] 修复潜在的Bug

最新更新见 b0e04315e80741f3e176015e820652d73c295f48
 
###### issue 催更是最舒服的，给你来个里程碑？

**Comment by Mr-SPM** [comment]
可以提功能需求→_→

**Comment by ShangHuanqing** [comment]
> 可以提功能需求→_→

等我用的时候我就提正经需求🌚

**Comment by ShangHuanqing** [comment]
没事去我毕设那加个Issue吧，不行的话，提交提交ReadMe也行，反正私有库，别人也不知道，自己太孤单了，我那个传了50多个Commit，然后技术过时了，Cao😂
